version: '3.2'

# Define services
services:
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    build:
      image: docker.pkg.github.com/brunosbastos/medex/backend:latest
    ports:
      - "8080:8080"
    restart: always
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/medex
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin_pass
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

  app-client:
    build:
      image: docker.pkg.github.com/brunosbastos/medex/frontend:latest
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:3000/
    ports:
      - "3000:3000"
    restart: always
    networks:
      - frontend

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:
