
name: Run Delivery

on:
  pull_request:
      branches:
          - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $DOCKER_PASSWORD | docker login https://docker.pkg.github.com -u BrunosBastos --password-stdin
    - name: Run deployment
      run: |
        docker-compose up -d
